= Contributing to Dependency Assistant

Dependency Assistant is released under the Apache 2.0 license.
If you would like to contribute something, or want to hack on the code this document should help you get started.

== Code of Conduct

This project adheres to the Contributor Covenant https://www.contributor-covenant.org/[code of conduct].
By participating, you are expected to uphold this code.
Please report unacceptable behavior.

== Using GitHub Issues

We use GitHub issues to track bugs and enhancements.
If you have a general usage question please ask on https://stackoverflow.com[Stack Overflow].

If you are reporting a bug, please help to speed up problem diagnosis by providing as much information as possible.
Ideally, that would include a small sample project that reproduces the problem.

== Code Conventions and Housekeeping

None of these is essential for a pull request, but they will all help.
They can also be added after the original pull request but before a merge.

* We provide a Java formatter at `etc/formatter.xml` to apply code formatting conventions.
* Make sure all new `.java` files have a Javadoc class comment with at least an `@author` tag identifying you, and preferably at least a paragraph on what the class is for.
* Add the ASF license header comment to all new `.java` files (copy from existing files in the project).
* Add yourself as an `@author` to the `.java` files that you modify substantially (more than cosmetic changes).
* Add some Javadocs.
* A few unit tests would help a lot as well.
* Verification tasks, including tests and Checkstyle, can be executed by running `./gradlew build` from the project root.
* If no-one else is using your branch, please rebase it against the current main branch (or other target branch in the project).
* When writing a commit message please follow https://cbea.ms/git-commit/[these conventions].