name: Build
on:
  push:
    branches: [ main ]
    tags: [ '*.*.*' ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  actions: write

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    outputs:
      name: ${{ steps.properties.outputs.name }}
      version: ${{ steps.properties.outputs.version }}
      changelog: ${{ steps.properties.outputs.changelog }}
      artifact: ${{ steps.properties.outputs.artifact }}
    steps:

      - name: Setup Java
        uses: actions/setup-java@v5.2.0
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Fetch Sources
        uses: actions/checkout@v6

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build Plugin
        run: ./gradlew check verifyPlugin buildPlugin

      - name: Capture Build Artifacts
        uses: actions/upload-artifact@v6
        with:
          name: plugin
          path: 'build/distributions/*.zip'
          retention-days: 15
